package com.pda.pda_android.db.greenDAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pda.pda_android.db.greenDAO.Apps;

import com.pda.pda_android.db.greenDAO.AppsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appsDaoConfig;

    private final AppsDao appsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appsDaoConfig = daoConfigMap.get(AppsDao.class).clone();
        appsDaoConfig.initIdentityScope(type);

        appsDao = new AppsDao(appsDaoConfig, this);

        registerDao(Apps.class, appsDao);
    }
    
    public void clear() {
        appsDaoConfig.clearIdentityScope();
    }

    public AppsDao getAppsDao() {
        return appsDao;
    }

}
