package com.pda.pda_android.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pda.pda_android.db.Entry.UserBean;
import com.pda.pda_android.db.Entry.SsxxUserInfoBean;
import com.pda.pda_android.db.Entry.JcjyBean;

import com.pda.pda_android.db.dao.UserBeanDao;
import com.pda.pda_android.db.dao.SsxxUserInfoBeanDao;
import com.pda.pda_android.db.dao.JcjyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig ssxxUserInfoBeanDaoConfig;
    private final DaoConfig jcjyBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final SsxxUserInfoBeanDao ssxxUserInfoBeanDao;
    private final JcjyBeanDao jcjyBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        ssxxUserInfoBeanDaoConfig = daoConfigMap.get(SsxxUserInfoBeanDao.class).clone();
        ssxxUserInfoBeanDaoConfig.initIdentityScope(type);

        jcjyBeanDaoConfig = daoConfigMap.get(JcjyBeanDao.class).clone();
        jcjyBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        ssxxUserInfoBeanDao = new SsxxUserInfoBeanDao(ssxxUserInfoBeanDaoConfig, this);
        jcjyBeanDao = new JcjyBeanDao(jcjyBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(SsxxUserInfoBean.class, ssxxUserInfoBeanDao);
        registerDao(JcjyBean.class, jcjyBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        ssxxUserInfoBeanDaoConfig.clearIdentityScope();
        jcjyBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public SsxxUserInfoBeanDao getSsxxUserInfoBeanDao() {
        return ssxxUserInfoBeanDao;
    }

    public JcjyBeanDao getJcjyBeanDao() {
        return jcjyBeanDao;
    }

}
